replicaCount: 2

image:
  repository: aqshey/argo_cd # Change this to your dockerhub_username/repo
  pullPolicy: IfNotPresent
  tag: "sha-be7422002639c83f6edbf9ab15c6f81f1b58ed9b"
  port: 5000

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
